version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dawanour2025/front-dep
    container_name: front-dep
    restart: always
    # ports:
    #   - "80:80"
    #   - "443:443"
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    #   - /var/www/certbot:/var/www/certbot
    #   - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - data-nour
networks:
  data-nour:
    external: true
    name: data-nour_default
# créer une image par cli depuis un Dockerfile:
#     docker build . -t abdennour2021/my-html-app
# créer un conteneur par cli:
#     docker run --name my-html-app-v1 -d -p 8081:80 abdennour2021/my-html-app
#http://127.0.0.1:82
# certbot certonly --webroot -w /var/www/certbot -d masjid-nour.org -d www.masjid-nour.org
# ls /etc/letsencrypt/live/masjid-nour.org/
# docker inspect front-dep --format='{{.State.Status}}'